### ISSUE TITLE
Move current tenderers to registrant

### ISSUE THREAD

**Issue by mpostelnicu** [OC-Bandung/newbirms#23]
Current tenderers are just `registrants`. 
- move them to new role `registrant`
- use `getOrganizationReferenceByName` to fill the registrants into `parties` array
- create new getTenderers function with the real tenderers
- change `getNumberOfTenderers` to read the number of tenderers from the real tenderers

**Comment by dc-coder** [comment]
I am not sure if the number of tenderers is generated or from a database. I noticed in some contracts, number of tenderers is 1 but then there are many suppliers and awards.

https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-38433

just thought to flag this.
