### ISSUE TITLE
API returns list or dict

### ISSUE THREAD

**Issue by odscjames** [OC-Bandung/newbirms#27]
https://birms.bandung.go.id/beta/api/contracts/year/2018?page=1 returns data as a list:

    {"current_page":1,"data":[{"ocid":"ocds-afzrfb-s-2018-15663169", .....

https://birms.bandung.go.id/beta/api/contracts/year/2018?page=2  returns data as a dict:

    {"current_page":2,"data":{"40":{"ocid":"ocds-afzrfb-s-2018-16244660",

It would be better if this was consistent in returning a list or a dict!

Thanks,

ps. I found this when working on https://github.com/open-contracting/ocdsdata/issues/203

**Comment by bdgcoder** [comment]
Its from function in laravel. I dont know how to do like that, maybe @mpostelnicu or @dc-coder know the better paging function for that.
