### ISSUE TITLE
500 errors

### ISSUE THREAD

**Issue by odscjames** [OC-Bandung/newbirms#28]
From

- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-36951
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-37917
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-39105
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-41516
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-42902
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-43122
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-43158
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-43362
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-43363
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-43961
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-44397
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-44458
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-44655
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-46490
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-48051
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-48215
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-48880
- https://birms.bandung.go.id/beta/api/newcontract/ocds-afzrfb-b-2016-49643

Thanks,

ps. Found when doing https://github.com/open-contracting/ocdsdata/issues/203

**Comment by bdgcoder** [comment]
Hi @odscjames i have been fix this. You can test again. Thx

**Comment by mpostelnicu** [comment]
some of them are fixed but some still have errors, @bdgcoder i updated the checker script and will provide complete error list for all years

**Comment by mpostelnicu** [comment]
@bdgcoder please check `getNonCompetitiveItems` function, you should add `distinct` to the sql covering all fields. the items array does not allow duplicate items, so an item has to differ from another item, if all the fields within an item are identical, it will trigger an error

**Comment by bdgcoder** [comment]
Ok thanks. I have been updated.

**Comment by mpostelnicu** [comment]
@odscjames all errors corrected, we have fetched and validated all entries against the schema. there should be no errors left.
