### ISSUE TITLE
Click on slider not working

### ISSUE THREAD

**Issue by dc-coder** [OC-Bandung/newbirms#4]
The slider elements  are not created dynamically. The click on slider dates no longer works. Change the JS click event for it to work

**Comment by dc-coder** [comment]
@bdgcoder 

- I updated the css to make the font size smaller
- I added a white background with some transparency to make the text easier to read
- I removed http://localhost/bandung2017 from the src of the image, now it is on /assets/media (let me know if ok)

As for the click and why it was not working, for the button, all of them were set to "nav__item--current".  The slider works only if there is one "nav__item--current". 

So, i added if condition in the class name. If it is the first item in the loop, the class is "nav__item" +  "nav__item--current" other otherwise it is only  "nav__item" 

`class="{{ $loop->first? 'nav__item nav__item--current' : 'nav__item' }}"`

**Comment by dc-coder** [comment]
There seems to be still one problem in the order of the images. but let's first test this and see if it works.

**Comment by bdgcoder** [comment]
I try to create <a href="..."> in slider, its not working. Same with top navigation. I don't know how to fix it
